#!/bin/bash



#修改默认的shell为bash，选择no
sudo dpkg-reconfigure dash

#更新源地址:http://wiki.ubuntu.org.cn/index.php?title=Qref/Source&variant=zh-cn
#安装完一个新系统时，首先更新源列表，后面工作会顺利很多，更新系统
sudo apt-get update && apt-get upgrade -y

#安装gcc,make工具
sudo apt-get install gcc
sudo apt-get install make

#安装图形文本编辑器
sudo apt-get install leafpad
sudo apt-get install gvim
sudo apt-get install automake libtool


#安装ZSH
sudo apt-get install git-core

git clone https://github.com/tracyone/linux-config 

sudo apt-get install zsh -y 

wget --no-check-certificate https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | sh 

cp ./linux-config/.zshrc ~ 


#安装传输工具ssh
#sudo scp ./dvrrdk.tar.gz root@192.168.1.48:/home //将dvrrdk.tar.gz拷贝到192.168.1.48这台远端机的home目录下
#sudo scp  root@192.168.1.48:/home/dvrrdk.tar.gz  ./   //将远端机的home目录下dvrrdk.tar.gz拷贝到当前目录下
sudo apt-get install openssh-server -y

sudo apt-get install subversion -y

#xiaobo 123987
svn co svn://192.168.1.2/ipnc_rdk/trunk ipnc_rdk
svn co svn://192.168.1.2/iss_03_50_00_00/trunk iss_03_50_00_00
svn co svn://192.168.1.2/hdvpss_01_00_01_37/trunk hdvpss_01_00_01_37
svn co svn://192.168.1.2/kernel/trunk kernel


echo "嵌入式开发.."
#sudo apt-get install putty -y
sudo apt-get install tftpd-hpa  tftp-hpa  xinetd -y
sudo apt-get install nfs-kernel-server -y
sudo apt-get install bison flex mtd-utils -y

echo "设置tftp..."
mkdir ~/tftpboot
chmod 777 ~/tftpboot
echo -e "RUN_DAEMON=\"yes\"" | sudo tee  /etc/default/tftpd-hpa
echo -e "OPTIONS=\"-l -s -c /home/$(whoami)/tftpboot\"" | sudo tee -a /etc/default/tftpd-hpa
echo -e "TFTP_USERNAME=\"root\"" | sudo tee -a /etc/default/tftpd-hpa
echo -e "TFTP_DIRECTORY=\"/home/$(whoami)/tftpboot\"" | sudo tee -a /etc/default/tftpd-hpa
echo -e "TFTP_ADDRESS=\"0.0.0.0:69\"" | sudo tee -a /etc/default/tftpd-hpa
echo -e "TFTP_OPTIONS=\"--secure\"" | sudo tee -a /etc/default/tftpd-hpa
sudo service tftpd-hpa restart

echo "设置nfs..."
mkdir ~/nfsroot
chmod 777 ~/nfsroot
#echo -e "/home/$(whoami)/nfsroot *(rw,no_root_squash,no_all_squash,sync)" | sudo tee -a /etc/exports
echo -e "/home/$(whoami)/nfsroot *(rw,nohide,insecure,no_subtree_check,async,no_root_squash)" | sudo tee -a /etc/exports
sudo exportfs -av
sudo service nfs-kernel-server restart 


#nfs export path
######IPNC###########

#8148EVM
/nfsroot/target/filesys  *(rw,nohide,insecure,no_subtree_check,async,no_root_squash)

#install rabbitvcs ;  请参考rabbitvcs官网安装步骤
sudo  add-apt-repository ppa:rabbitvcs/ppa
#Add the following line to your /etc/apt/sources.list file
#deb http://ppa.launchpad.net/rabbitvcs/ppa/ubuntu **DISTRIBUTION** main
 su root 
 
 echo "deb http://ppa.launchpad.net/rabbitvcs/ppa/ubuntu **DISTRIBUTION** main"  >/etc/apt/sources.list 

 sudo apt-get update 
 #update source-list:
 #refer link : http://wiki.ubuntu.org.cn/Qref/Source       
 
 sudo apt-get install rabbitvcs-nautilus3 rabbitvcs-thunar rabbitvcs-gedit rabbitvcs-cli  thunar-vcs-plugin 
#After installation is complete, logout and log back in for changes to take effect. 
#find the app and copy  to desktop : such as : /usr/share/applications/nautilus.desktop


#install samba
sudo apt-get install samba cifs-utils
sudo cp /etc/samba/smb.conf /etc/samba/smb.conf.bak
sudo touch /etc/samba/smbpasswd
sudo smbpasswd -a afa 
sudo service samba restart || sudo service smbd restart 
Debian changed service from 'samba' to 'smbd'. Closes GH-17 … 

#config
[share]
        comment = Shared Folder with username and password
	path = /tftpboot/DM812x/nand
	public = yes
	writable = no
	valid users = afa
	create mask = 0700
	directory mask = 0700
	force user = nobody
	force group = nogroup
	available = yes
	browseable = yes
	workgroup = WORKGROUP
	display charset = UTF-8
	unix charset = UTF-8
	dos charset = cp936


#sudo apt-get install 安装自动补全
#1、安装bash-completion
apt-get install bash-completion

#2、编辑~/.bashrc 文件，添加如下内容：
if [ -f /etc/bash_completion ]; then
. /etc/bash_completion
fi

#3、使其生效 ，退出SSH，重新登录。

#删除安装后的软件包
sudo apt-get clean #- 删除所有已下载的包文件
sudo apt-get autoclean #- 删除老版本的已下载的包文件
sudo apt-get check #- 核对以确认系统的依赖关系的完整性

#还有个狠的，要是你不在乎今后的升级的话，
rm -rf /var/cache/apt

#查看linux发行的版本号
cat /etc/issue.net 
cat /etc/os-release
uname -a 
cat /proc/version

#多线程编译，加快编译速度
make -j 20  #支持20个线程同时编译



